# Generated by Django 4.0.5 on 2022-06-13 08:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mapbox_location_field.models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prof_pic', models.ImageField(blank=True, upload_to='media')),
                ('bio', models.TextField(blank=True, max_length=255)),
                ('website', models.URLField(blank=True, max_length=50)),
                ('name', models.CharField(blank=True, max_length=50)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None)),
                ('fax_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None)),
                ('linkedin', models.URLField(blank=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, max_length=500)),
                ('project_image', models.ImageField(upload_to='media')),
                ('project_url', models.URLField(max_length=255)),
                ('created_on', models.DateField(auto_now_add=True)),
                ('location', mapbox_location_field.models.LocationField(blank=True, map_attrs={})),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='awards.profile')),
            ],
        ),
        migrations.CreateModel(
            name='UsabilityVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_voted', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usability_likes', to='awards.project')),
                ('profile_vote', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='awards.profile')),
            ],
        ),
        migrations.CreateModel(
            name='DesignVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_voted', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='design_likes', to='awards.project')),
                ('profile_vote', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='awards.profile')),
            ],
        ),
        migrations.CreateModel(
            name='ContentVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_voted', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='content_likes', to='awards.project')),
                ('profile_vote', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='awards.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_comment', models.CharField(max_length=255)),
                ('project_associated', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='awards.project')),
                ('user_profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='awards.profile')),
            ],
        ),
    ]
