# Generated by Django 4.0.5 on 2022-06-13 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0002_remove_project_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='fax_number',
        ),
    ]
