# Generated by Django 4.0.5 on 2022-06-12 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0005_rename_project_site'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='phone_number',
            field=models.IntegerField(blank=True, max_length=10),
        ),
    ]
